### ISSUE TITLE
RuntimeError: No kernel named  XXX was found -46 (PI_ERROR_INVALID_KERNEL_NAME)

### ISSUE THREAD

**Issue by jinz2014** [intel/intel-extension-for-pytorch#330]
### Describe the issue

IPEX developers,
Did you observe the runtime error when running a Pytorch program with the DPC++ extension on an Intel GPU ? Thank you for your solution.

https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/features/DPC%2B%2B_Extension.html

Environment
Ubuntu 
python 3.10
torch_version:       1.13.0a0+git49444c3
torchvision_version: 0.14.1a0+5e8e2f1
torchaudio_version:  0.13.1+b90d798
ipex_version:        1.13.120+git5fdf9e6

Reference
https://github.com/intel/llvm/issues/6421

**Comment by jingxu10** [comment]
@tye1

**Comment by arthuryuan1987** [comment]
Looks like a SYCL runtime error. Can you post you SYCL kernel code?

**Comment by jinz2014** [comment]
I am confused whether the issue was related to the compiler.  When running a Python program to test some SYCL kernel using the DPCPP extension on an Intel GPU, did you observe the runtime error ?  

Will you consider adding some examples in a github repository for the tutorial (https://intel.github.io/intel-extension-for-pytorch/xpu/latest/tutorials/features/DPCPP_Extension.html) ? Thanks.

**Comment by tye1** [comment]
@jinz2014  This issue has been fixed in latest xpu-master. Could you please verify and close this issue?

**Comment by jinz2014** [comment]
I close the issue. Thanks.
