### ISSUE TITLE
`index_select` fails on XPU when big indices are provided

### ISSUE THREAD

**Issue by DamianSzwichtenberg** [intel/intel-extension-for-pytorch#467]
### Describe the bug

In GNNs, `index_select` is quite a common operation, I noticed that when I'm using a very big batch size, this operation fails with the following error:
```python
RuntimeError: Provided range is out of integer limits. Pass `-fno-sycl-id-queries-fit-in-int' to disable range check. -30 (PI_ERROR_INVALID_VALUE)
```
This error occurs only when XPU is a target device. Below is a minimal code to reproduce this:
```python
import torch
import intel_extension_for_pytorch  # 2.0.1


src = torch.rand((256000, 128))
index = torch.randint(0, src.size(0), (32000000, ))
# works well on CPU
src.index_select(0, index)

src = src.to('xpu')
index = index.to('xpu')
# fails on GPU with the following error:
# RuntimeError: Provided range is out of integer limits. Pass `-fno-sycl-id-queries-fit-in-int' to disable range check. -30 (PI_ERROR_INVALID_VALUE)
src.index_select(0, index)
```

### Versions

```
PyTorch version: 2.0.1a0+gite9ebda2
PyTorch CXX11 ABI: Yes
IPEX version: 2.0.110+git509a378
IPEX commit: 509a3789d
Build type: Release

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: N/A
IGC version: 2023.1.0 (2023.1.0.20230320)
CMake version: version 3.27.1
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.0-41-generic-x86_64-with-glibc2.35
Is XPU available: True
DPCPP runtime version: 2023.1.0
MKL version: 2023.1.0
GPU models and configuration:
[0] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=1, total_memory=62244MB, max_compute_units=448, gpu_eu_count=448)
[1] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=1, total_memory=62244MB, max_compute_units=448, gpu_eu_count=448)
Intel OpenCL ICD version: 23.17.26241.21-647~22.04
Level Zero version: 1.3.26241.21-647~22.04

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          64
On-line CPU(s) list:             0-63
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8352Y CPU @ 2.20GHz
CPU family:                      6
Model:                           106
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       1
Stepping:                        6
CPU max MHz:                     3400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4400.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       1.5 MiB (32 instances)
L1i cache:                       1 MiB (32 instances)
L2 cache:                        40 MiB (32 instances)
L3 cache:                        48 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-63
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.0.110+git509a378
[pip3] numpy==1.25.2
[pip3] torch==2.0.1a0+gite9ebda2
[pip3] torch_geometric==2.4.0
[pip3] torch-geometric-benchmark==0.1.0
[pip3] torch-scatter==2.1.1
[pip3] torch-sparse==0.6.17
[conda] intel-extension-for-pytorch 2.0.110+git509a378          pypi_0    pypi
[conda] numpy                     1.25.2                   pypi_0    pypi
[conda] torch                     2.0.1a0+gite9ebda2          pypi_0    pypi
[conda] torch-geometric           2.4.0                    pypi_0    pypi
[conda] torch-geometric-benchmark 0.1.0                     dev_0    <develop>
[conda] torch-scatter             2.1.1                     dev_0    <develop>
[conda] torch-sparse              0.6.17                    dev_0    <develop>
```

**Comment by tye1** [comment]
@DamianSzwichtenberg  thanks for reporting, we will try to reproduce.

**Comment by MarekStrachacki** [comment]
@tye1 - any update on this?

**Comment by tye1** [comment]
We are able to reproduce the issue. Will investigate the root cause.

**Comment by MarekStrachacki** [comment]
@tye1 - did you find the root cause?

**Comment by tye1** [comment]
@MarekStrachacki  Sorry for the late response. We have root caused it and will provide a fix soon. Once ready, will update here.

**Comment by tye1** [comment]
@MarekStrachacki  we have fixed this issue in our latest release. Could you please help to verify?

Please refer to https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.1.30%2bxpu&os=linux%2fwsl2&package=pip for the installation.

**Comment by nihilityer** [comment]
@tye1 
On Windows system I got the same exception when using `ComfyUI-layerdiffuse`, are they the same cause?
```
RuntimeError: Provided range is out of integer limits. Pass `-fno-sycl-id-queries-fit-in-int' to disable range check.
```
Hardware:
```
A770 16G
```
Version:
```
torch==2.1.0.post2 
torchvision==0.16.0.post2 
torchaudio==2.1.0.post2
intel-extension-for-pytorch==2.1.30
```
Error Message:
```
Traceback (most recent call last):
  File "C:\Users\***\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\***\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\***\AI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\***\ComfyUI\custom_nodes\ComfyUI-layerdiffuse\layered_diffusion.py", line 198, in decode
    image, mask = super().decode(samples, images, sd_version, sub_batch_size)
  File "C:\Users\***\ComfyUI\custom_nodes\ComfyUI-layerdiffuse\layered_diffusion.py", line 174, in decode
    self.vae_transparent_decoder[sd_version].decode_pixel(
  File "C:\Users\***\.conda\envs\comfyui\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\***\Documents\AI\ComfyUI\custom_nodes\ComfyUI-layerdiffuse\lib_layerdiffusion\models.py", line 314, in decode_pixel
    y = self.estimate_augmented(pixel, latent)
  File "C:\Users\***\.conda\envs\comfyui\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\***\Documents\AI\ComfyUI\custom_nodes\ComfyUI-layerdiffuse\lib_layerdiffusion\models.py", line 299, in estimate_augmented
    median = torch.median(result, dim=0).values
RuntimeError: Provided range is out of integer limits. Pass `-fno-sycl-id-queries-fit-in-int' to disable range check.
```

**Comment by tye1** [comment]
The error message is the same but the issue might exist in a different place. We will try to reproduce firstly. @jingxu10  please help.

**Comment by wangkl2** [comment]
According to @nihilityer in https://github.com/intel/intel-extension-for-pytorch/issues/630, this issue in `ComfyUI-layerdiffuse` has been fixed.

**Comment by wangkl2** [comment]
@DamianSzwichtenberg Using IPEX 2.1.30+xpu, the `index_select` for large indexing works well on Max GPU on my side. Please help verify. Thanks.

**Comment by tye1** [comment]
Let me close this issue, feel free to reopen or create a new issue if you encounter any issue again.

**Comment by arekkulczycki** [comment]
I encounter this same problem with Arc A770, intel oneapi 2025.0 in arch linux, and the following versions
```
intel-cmplr-lib-rt==2025.0.4
intel-cmplr-lib-ur==2025.0.4
intel-cmplr-lic-rt==2025.0.4
intel-extension-for-openxla==0.2.0
intel-opencl-rt==2025.0.4
intel-openmp==2025.0.4
intel-pti==0.10.0
intel-sycl-rt==2025.0.4
intel_extension_for_pytorch==2.5.10+xpu
torch==2.5.1+cxx11.abi
torch_geometric==2.5.2
torchaudio==2.5.1+cxx11.abi
torchmetrics==1.3.2
torchrl==0.3.1
torchvision==0.20.1+cxx11.abi
```

I don't know if that matters but it happens while using graph convolution classes from pytorch-geometric (tried with `SAGEConv` and `GCNConv`).

Was the error re-introduced in 2.5.10? Is there something I can do on my side to prevent the issue from happening?
