### ISSUE TITLE
Native API failed. Native API returns: -2 (PI_ERROR_DEVICE_NOT_AVAILABLE) -2 (PI_ERROR_DEVICE_NOT_AVAILABLE)

### ISSUE THREAD

**Issue by MaksimDanilov** [intel/intel-extension-for-pytorch#643]
### Describe the bug

I made program that waits to input image to be segmentated though U2NET model. After some inputs (can't determine frequency as it is always random), I start to get DEVICE_NOT_AVAILABLE_ERROR when I post tensor to xpu.  Can I somehow get debug logs to post here?

\* I noticed that with the same program I can't reproduce this error on cpu)
** It happens only if I have transferred data to model. Simple forward data to xpu works file.

### Versions

Collecting environment information...
PyTorch version: 2.1.0.post2+cxx11.abi
PyTorch CXX11 ABI: No
IPEX version: 2.1.30+xpu
IPEX commit: https://github.com/intel/intel-extension-for-pytorch/commit/474a6b3cb2a0b996d47859a2290415487cb0534f
Build type: Release

OS: Microsoft Windows 11 Home
GCC version: N/A
Clang version: N/A
IGC version: 2024.1.0 (2024.1.0.20240308)
CMake version: version 3.28.0-msvc1
Libc version: N/A

Python version: 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22631-SP0
Is XPU available: True
DPCPP runtime version: N/A
MKL version: N/A
GPU models and configuration:
[0] _DeviceProperties(name='Intel(R) Iris(R) Xe Graphics', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.29283', has_fp64=0, total_memory=7167MB, max_compute_units=96, gpu_eu_count=96)
Intel OpenCL ICD version: N/A
Level Zero version: N/A

CPU:

Revision=

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.1.30+xpu
[pip3] numpy==1.26.1
[pip3] torch==2.1.0.post2+cxx11.abi
[pip3] torchaudio==2.1.0.post2+cxx11.abi
[pip3] torchvision==0.16.0.post2+cxx11.abi
[conda] intel-extension-for-pytorch 2.1.30+xpu pypi_0 pypi
[conda] numpy 1.26.1 pypi_0 pypi
[conda] torch 2.1.0.post2+cxx11.abi pypi_0 pypi
[conda] torchaudio 2.1.0.post2+cxx11.abi pypi_0 pypi
[conda] torchvision 0.16.0.post2+cxx11.abi pypi_0 pypi

### Code

```python

import torch
import intel_extension_for_pytorch as ipex

import logging


class TinyModel(torch.nn.Module):
    def __init__(self):
        super(TinyModel, self).__init__()

        self.linear1 = torch.nn.Linear(750, 1000)
        self.activation = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(1000, 2)
        self.softmax = torch.nn.Softmax()

    def forward(self, x):
        x = self.linear1(x)
        x = self.activation(x)
        x = self.linear2(x)
        x = self.softmax(x)
        return x


device = 'xpu'
dtype = torch.float32

model = TinyModel()
model.eval() # Set the model to evaluation mode for inference, as required by ipex.optimize() function.
data = torch.zeros(750, dtype=dtype)[None]

model = model.to(device)
model = ipex.optimize(model, weights_prepack=False)

if __name__ == "__main__":
    while True:
        try:
            input('Press Any Key To Continue...')

            logging.info(f'Available: {ipex.xpu.is_available()}.')
            logging.info('Started.')

            with torch.no_grad():
                model(data.to(device))

            logging.info('Forwarded.')

        except KeyboardInterrupt:
            break

        except EOFError:
            break

        except Exception as ex:
            logging.exception(ex)
```

**Comment by nazneenn** [comment]
Hi @MaksimDanilov, thanks for reporting this issue. Could you please help provide the Traceback error from your terminal using
```python script.py &> ./log.txt```

Please also verify the driver installation version from here:
https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu

**Comment by MaksimDanilov** [comment]
![Uploading anydesk00000.png…]()

**Comment by MaksimDanilov** [comment]
![anydesk00000](https://github.com/intel/intel-extension-for-pytorch/assets/47329914/f8ee8def-2104-4df2-adf1-e10f314040cb)

**Comment by MaksimDanilov** [comment]
C:\Users\alco_\miniconda3\envs\torch_tesr\Lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 'Could not find module 'C:\Users\alco_\miniconda3\envs\torch_tesr\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Using xpu device
C:\Users\alco_\miniconda3\envs\torch_tesr\Lib\site-packages\torch\overrides.py:110: UserWarning: 'has_cuda' is deprecated, please use 'torch.backends.cuda.is_built()'
  torch.has_cuda,
C:\Users\alco_\miniconda3\envs\torch_tesr\Lib\site-packages\torch\overrides.py:111: UserWarning: 'has_cudnn' is deprecated, please use 'torch.backends.cudnn.is_available()'
  torch.has_cudnn,
C:\Users\alco_\miniconda3\envs\torch_tesr\Lib\site-packages\torch\overrides.py:117: UserWarning: 'has_mps' is deprecated, please use 'torch.backends.mps.is_built()'
  torch.has_mps,
C:\Users\alco_\miniconda3\envs\torch_tesr\Lib\site-packages\torch\overrides.py:118: UserWarning: 'has_mkldnn' is deprecated, please use 'torch.backends.mkldnn.is_available()'
  torch.has_mkldnn,
C:\Users\alco_\miniconda3\envs\torch_tesr\Lib\site-packages\torch\nn\functional.py:3769: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
[__optimize] 6.355390310287476 seconds
initialized
> >? -i C:\tmp\floor-ceiling-segmentation-m.danilov-feature-terminal\data\floor_dataset_1_1.jpg -o test.jpg
[__load] 0.022661685943603516 seconds
[__rescale] 0.0009648799896240234 seconds
[__to_lab] 0.01090383529663086 seconds
[__load_data_to_device] 0.020354747772216797 seconds
[__process] 0.0396270751953125 seconds
[__norm_pred] 0.09251761436462402 seconds
[__save_output] 0.290982723236084 seconds
[process] 0.4810492992401123 seconds
1

## after 10 minutes (its always random)

> >? -i C:\tmp\floor-ceiling-segmentation-m.danilov-feature-terminal\data\floor_dataset_1_1.jpg -o test.jpg
[__load] 0.0019996166229248047 seconds
[__rescale] 0.0 seconds
[__to_lab] 0.009001016616821289 seconds
2024-05-31 11:06:31,174 - root - ERROR - Native API failed. Native API returns: -2 (PI_ERROR_DEVICE_NOT_AVAILABLE) -2 (PI_ERROR_DEVICE_NOT_AVAILABLE)
Traceback (most recent call last):
  File "C:\tmp\floor-ceiling-segmentation-m.danilov-feature-terminal\src\floor_ceiling_segmentation\terminal.py", line 22, in main
    process(input_filepath=args.input, output_filepath=args.output, debug=args.debug)
  File "C:\tmp\floor-ceiling-segmentation-m.danilov-feature-terminal\src\floor_ceiling_segmentation\demo.py", line 16, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\tmp\floor-ceiling-segmentation-m.danilov-feature-terminal\src\floor_ceiling_segmentation\demo.py", line 170, in process
    inputs_test = __load_data_to_device(img)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tmp\floor-ceiling-segmentation-m.danilov-feature-terminal\src\floor_ceiling_segmentation\demo.py", line 16, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\tmp\floor-ceiling-segmentation-m.danilov-feature-terminal\src\floor_ceiling_segmentation\demo.py", line 168, in __load_data_to_device
    return tensor[None].to(DEVICE, dtype=torch.float32)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Native API failed. Native API returns: -2 (PI_ERROR_DEVICE_NOT_AVAILABLE) -2 (PI_ERROR_DEVICE_NOT_AVAILABLE)
0
> >? -i C:\tmp\floor-ceiling-segmentation-m.danilov-feature-terminal\data\floor_dataset_1_1.jpg -o test.jpg
[__load] 0.0009982585906982422 seconds
[__rescale] 0.0 seconds
[__to_lab] 0.008350372314453125 seconds
0
> 2024-05-31 11:06:33,687 - root - ERROR - Native API failed. Native API returns: -999 (Unknown PI error) -999 (Unknown PI error)
Traceback (most recent call last):
  File "C:\tmp\floor-ceiling-segmentation-m.danilov-feature-terminal\src\floor_ceiling_segmentation\terminal.py", line 22, in main
    process(input_filepath=args.input, output_filepath=args.output, debug=args.debug)
  File "C:\tmp\floor-ceiling-segmentation-m.danilov-feature-terminal\src\floor_ceiling_segmentation\demo.py", line 16, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\tmp\floor-ceiling-segmentation-m.danilov-feature-terminal\src\floor_ceiling_segmentation\demo.py", line 170, in process
    inputs_test = __load_data_to_device(img)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\tmp\floor-ceiling-segmentation-m.danilov-feature-terminal\src\floor_ceiling_segmentation\demo.py", line 16, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\tmp\floor-ceiling-segmentation-m.danilov-feature-terminal\src\floor_ceiling_segmentation\demo.py", line 168, in __load_data_to_device
    return tensor[None].to(DEVICE, dtype=torch.float32)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Native API failed. Native API returns: -999 (Unknown PI error) -999 (Unknown PI error)

**Comment by MaksimDanilov** [comment]
Update issue description 'cause it's only reproduce if I post data to model.

**Comment by nazneenn** [comment]
Is it possible to provide us with a minimum code reproducer for this issue as well as the test image? Thanks.

**Comment by MaksimDanilov** [comment]
Okey. Try to make minimal example on weekends.

**Comment by MaksimDanilov** [comment]
Add code to description. Also paste log with time measures when the exception was thrown. 
[log.txt](https://github.com/user-attachments/files/15522713/log.txt)

**Comment by nazneenn** [comment]
Thank you for providing the sample code. I could not reproduce the same error at my end.

Could we test if the Intel® oneAPI Base Toolkit 2024.1.0 is installed and sourced correctly? In your collected environment information, I noticed that the DPCPP and MKL versions are listed as N/A. 
Please run the sanity check test to double confirm if the correct version is installed. Please verify according to this documentation for windows.
https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.1.30%2bxpu&os=windows&package=pip
```
call {DPCPPROOT}\env\vars.bat
call {MKLROOT}\env\vars.bat
python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.__version__); print(ipex.__version__); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"
```

**Comment by MaksimDanilov** [comment]
Okey. I didn't invoke these two bat's like that. I use setvars bat in root directory of OneApi.

**Comment by MaksimDanilov** [comment]
![image](https://github.com/intel/intel-extension-for-pytorch/assets/47329914/14c1f52e-2058-4c35-ba71-d71132714bd6)

**Comment by MaksimDanilov** [comment]
Maybe I should set root vars explicitly. I try it out now.

**Comment by MaksimDanilov** [comment]
@nazneenn Maybe I can search for debug logs if exists to help you understand this problem a bit more?

**Comment by ziyanxzy** [comment]
i have the same problem. when i choose dataset "piqa" limit 5 ,it can work. but if i use limit10/20/50 and more cases, it can not.
![image](https://github.com/intel/intel-extension-for-pytorch/assets/109060006/e32c32dd-e63f-47f0-9d9e-2725d37241c2)

**Comment by nazneenn** [comment]
> @nazneenn Maybe I can search for debug logs if exists to help you understand this problem a bit more?

@MaksimDanilov, you may try any debugger like gdb or python debugger to get more details on the issue and report back what you see when the core dump happens:
```python -m pdb your_script.py```

**Comment by ziyanxzy** [comment]
> > @nazneenn Maybe I can search for debug logs if exists to help you understand this problem a bit more?
> 
> @MaksimDanilov, you may try any debugger like gdb or python debugger to get more details on the issue and report back what you see when the core dump happens: `python -m pdb your_script.py`

[Image]

**Comment by ziyanxzy** [comment]
![image](https://github.com/intel/intel-extension-for-pytorch/assets/109060006/77d8d1af-3cea-4bda-835a-5170399d3e0b)


> > @nazneenn Maybe I can search for debug logs if exists to help you understand this problem a bit more?
> 
> @MaksimDanilov, you may try any debugger like gdb or python debugger to get more details on the issue and report back what you see when the core dump happens: `python -m pdb your_script.py`
![image](https://github.com/intel/intel-extension-for-pytorch/assets/109060006/701e130d-d919-41ae-a9a2-796ab1855c40)

**Comment by MaksimDanilov** [comment]
I can always reproduce this problem now step by step:
1. Prepare loop-forever script.
2. Init model and send it to xpu with optimization.
3. Send tensor to gpu.
4. Wait ~6-7 minutes.
5. Try 2 and 3.
6. Get this error. In system logs when I tried to push data to tensor I see "Display driver igfx stopped responding and has successfully recovered". (When I tried to change TdrDelay to 60 secs my device freezes forever)

**Comment by nazneenn** [comment]
Hi @MaksimDanilov , 
Has this issue been resolved? #659 where you have mentioned that you resolved it by compiling an extension with AOT='dg1.'
Thanks

**Comment by MaksimDanilov** [comment]
> Hi @MaksimDanilov , Has this issue been resolved? #659 where you have mentioned that you resolved it by compiling an extension with AOT='dg1.' Thanks

Hi :-)
No, after I compiled dll, I can't reduce AOT so related task is about that. Don't know what to do now, 'cause I need to have two separated process to have loaded model to GPU and working like command terminal to do tasks for time of main program executed.

Still have problem after pushing tensor to GPU after 5-6 minutes (first try pass successfully). When I launch second process and my gpu memory is running low, catch similar error. Maybe problem in swapping or something like that, because the loading freezes after some time.
All the time it fails with ifqnx driver was restarted by Windows in system events.

**Comment by yinghu5** [comment]
Hi @MaksimDanilov ,

I try the issue on one Xe Irs machine, it seems everything goes fine.  I post my step here, could you please try again and see if it can resolved the problem? 

![image](https://github.com/user-attachments/assets/05ffca9c-94d7-47bc-8090-3008c45293fd)

**Comment by MaksimDanilov** [comment]
@yinghu5 Hi, thanks for reply.
I tried to do as you say, but got the same problem. Can you wait after first pass a bit longer (~10 minutes).
![anydesk00003](https://github.com/user-attachments/assets/dbcc8436-c6ef-4fe6-8b3f-12ce6f5d5554)

**Comment by yinghu5** [comment]
@MaksimDanilov ,  Thank you for raising the issue to Driver team.  I will check with them about the problem internally. 
 I can reproduce the problem click after first pass a bit longer (~10 minutes). It seems the driver dis-connect the CPU and XPU if  some break. 

Press Any Key To Continue...
2024-08-16 08:49:19,646 - root - INFO - Available: True.
2024-08-16 08:49:19,646 - root - INFO - Started.
2024-08-16 08:49:19,646 - root - INFO - Forwarded.
Press Any Key To Continue...
2024-08-16 09:01:54,091 - root - INFO - Available: True.
2024-08-16 09:01:54,091 - root - INFO - Started.
2024-08-16 09:01:54,615 - root - ERROR - Native API failed. Native API returns: -2 (PI_ERROR_DEVICE_NOT_AVAILABLE) -2 (PI_ERROR_DEVICE_NOT_AVAILABLE)
Traceback (most recent call last):
  File "C:\Users\yhu5\test.py", line 44, in <module>
    model(data.to(device))
          ^^^^^^^^^^^^^^^
RuntimeError: Native API failed. Native API returns: -2 (PI_ERROR_DEVICE_NOT_AVAILABLE) -2 (PI_ERROR_DEVICE_NOT_AVAILABLE)
Press Any Key To Continue...

**Comment by yinghu5** [comment]
Hi @MaksimDanilov ,  
we have new release for IPEX and driver recently. I tried them and seems the issue was gone.  Would you please to try it and let us know if any result:
IPEX:  IPEX 2.5.10 XPU
https://pytorch-extension.intel.com/installation?platform=gpu&version=v2.5.10%2Bxpu&os=windows&package=pip
Driver：  32.0.101.6314
you may install more latest version from
https://www.intel.com/content/www/us/en/download/785597/intel-arc-iris-xe-graphics-windows.html
the `import torch
import intel_extension_for_pytorch as ipex

import logging

import time  

# Configure the logging  
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s') 

class TinyModel(torch.nn.Module):
    def __init__(self):
        super(TinyModel, self).__init__()

        self.linear1 = torch.nn.Linear(750, 1000)
        self.activation = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(1000, 2)
        self.softmax = torch.nn.Softmax(dim=0)

    def forward(self, x):
        x = self.linear1(x)
        x = self.activation(x)
        x = self.linear2(x)
        x = self.softmax(x)
        return x

device = 'xpu'
dtype = torch.float32

model = TinyModel()
model.eval() # Set the model to evaluation mode for inference, as required by ipex.optimize() function.
data = torch.zeros(750, dtype=dtype)[None]

model = model.to(device)
model = ipex.optimize(model, weights_prepack=False)

if __name__ == "__main__":
    while True:
        try:
            input('Press Any Key To Continue...')

           # logging.info(f'Available: {torch.xpu.is_available()}. ')
            logging.info(f'Available: {torch.xpu.is_available()}.')
            logging.info('Started.')

            with torch.no_grad():
                model(data.to(device))

            logging.info('Forwarded.')

        except KeyboardInterrupt:
            break

        except EOFError:
            break

        except Exception as ex:
            logging.exception(ex)`
![image](https://github.com/user-attachments/assets/28bc71ca-2b7b-4780-8edc-565fa7c722ab)
