### ISSUE TITLE
FSDP raises ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY in multi-node usage

### ISSUE THREAD

**Issue by garrett361** [intel/intel-extension-for-pytorch#646]
### Describe the bug

When using two Intel GPU 1550 nodes, Fully Sharded Data Parallel raises OOM errors
(`ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY`), similar to #640 .

Tested by wrapping a simple linear model: [code here](https://gist.github.com/garrett361/1f016056c1edc156bbad7be57c724d4f). Running the script with the default settings raises the OOM:

```bash
Using Versions: torch.__version__='2.1.0.post2+cxx11.abi', ipex.__version__='2.1.30.post0', torch_ccl.__version__='2.1.300+xpu'
****************************************
Running max_steps=500, batch_size=1 across 24 GPUs with

model=LinearModel(
  (linears): ModuleList(
    (0-3): 4 x Linear(in_features=16384, out_features=16384, bias=True)
  )
)

Num parameters: 1.07e+09
GiB: 4.00e+00
****************************************
[rank=6]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=8]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=2]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=4]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=11]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=9]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=3]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=0]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=1]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=7]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=10]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=5]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=14]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=13]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=18]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=20]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=21]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=23]: step=1 memory peak_mem_GiB=5.083704948425293, current_mem_GiB=0.3334164619445801
[rank=19]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=16]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=17]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=15]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=22]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=12]: step=1 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801

[ ... snip ...]

[rank=17]: step=13 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=21]: step=13 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=19]: step=13 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=16]: step=13 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=15]: step=13 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=23]: step=13 memory peak_mem_GiB=5.083704948425293, current_mem_GiB=0.3334164619445801
[rank=22]: step=13 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
[rank=12]: step=13 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=0.3334164619445801
2024:06:03-19:33:46:( 8495) |CCL_ERROR| worker.cpp:338 ccl_worker_func: worker 0 caught internal exception: oneCCL: ze_call.cpp:28 do_call: EXCEPTION: ze error at zeCommandQueueExecuteCommandLists, code: ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY
terminate called after throwing an instance of 'ccl::v1::exception'
  what():  oneCCL: ze_call.cpp:28 do_call: EXCEPTION: ze error at zeCommandQueueExecuteCommandLists, code: ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY

[ ... snip ...]
```

Tested in three different environments:

| `torch/torch-ccl/ipex` Versions                | `FSDP` Result                          |
| ---------------------------------------------- | -------------------------------------- |
| 2.1.0a0+cxx11.abi/2.1.10+xpu/2.1.100+xpu       | `ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY` |
| 2.1.0.post2+cxx11.abi/2.1.300+xpu/2.1.30+xpu   | `ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY` |
| 2.1.0.post2+cxx11.abi/2.1.300+xpu/2.1.30.post0 | `ZE_RESULT_ERROR_OUT_OF_DEVICE_MEMORY` |

Note this is slightly different from #640 in which the version set in the first line did not lead to an error. I have not yet been able to narrow down the issue in the present case to a single collective.

### Versions

Tested in three environments:

# Environment 1

```
Collecting environment information...
PyTorch version: 2.1.0a0+cxx11.abi
PyTorch CXX11 ABI: Yes
IPEX version: 2.1.10+xpu
IPEX commit: a12f9f650
Build type: Release

OS: SUSE Linux Enterprise Server 15 SP4 (x86_64)
GCC version: (Spack GCC) 12.2.0
Clang version: N/A
IGC version: 2024.0.0 (2024.0.0.20231017)
CMake version: version 3.27.5
Libc version: glibc-2.31

Python version: 3.9.18 (tags/v3.9.18-26-g6b320c3b2f6-dirty:6b320c3b2f6, Sep 28 2023, 00:35:27)  [GCC 13.2.0] (64-bit runtime)
Python platform: Linux-5.14.21-150400.24.55-default-x86_64-with-glibc2.31
Is XPU available: True
DPCPP runtime version: latest
MKL version: latest
GPU models and configuration: 
[0] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[1] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[2] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[3] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[4] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[5] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[6] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[7] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[8] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[9] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[10] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[11] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu, support_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
Intel OpenCL ICD version: N/A
Level Zero version: N/A

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          208
On-line CPU(s) list:             0-207
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU Max 9470C
CPU family:                      6
Model:                           143
Thread(s) per core:              2
Core(s) per socket:              52
Socket(s):                       2
Stepping:                        8
Frequency boost:                 enabled
CPU max MHz:                     2001.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4000.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr avx512_fp16 amx_tile flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       4.9 MiB (104 instances)
L1i cache:                       3.3 MiB (104 instances)
L2 cache:                        208 MiB (104 instances)
L3 cache:                        210 MiB (2 instances)
NUMA node(s):                    4
NUMA node0 CPU(s):               0-51,104-155
NUMA node1 CPU(s):               52-103,156-207
NUMA node2 CPU(s):               
NUMA node3 CPU(s):               
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.1.10+xpu
[pip3] numpy==1.24.4
[pip3] torch==2.1.0a0+cxx11.abi
[pip3] torch-tb-profiler==0.4.3
[pip3] torchvision==0.16.2
[conda] intel-extension-for-pytorch 2.1.10+xpu               pypi_0    pypi
[conda] mkl                       2024.0.0            intel_49630    intel
[conda] mkl-dpcpp                 2024.0.0            intel_49630    intel
[conda] mkl-service               2.4.0           py39h3539a15_40    intel
[conda] mkl_fft                   1.3.6           py39h1d81ff8_61    intel
[conda] mkl_random                1.2.2           py39h5a378b4_81    intel
[conda] mkl_umath                 0.1.1           py39h2b1685c_91    intel
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] onemkl-sycl-blas          2024.0.0            intel_49630    intel
[conda] onemkl-sycl-datafitting   2024.0.0            intel_49630    intel
[conda] onemkl-sycl-dft           2024.0.0            intel_49630    intel
[conda] onemkl-sycl-lapack        2024.0.0            intel_49630    intel
[conda] onemkl-sycl-rng           2024.0.0            intel_49630    intel
[conda] onemkl-sycl-sparse        2024.0.0            intel_49630    intel
[conda] onemkl-sycl-stats         2024.0.0            intel_49630    intel
[conda] onemkl-sycl-vm            2024.0.0            intel_49630    intel
[conda] torch                     2.1.0a0+cxx11.abi          pypi_0    pypi
[conda] torchvision               0.16.2                   pypi_0    pypi
```

# Environment 2

```
Collecting environment information...
PyTorch version: 2.1.0.post2+cxx11.abi
PyTorch CXX11 ABI: Yes
IPEX version: 2.1.30+xpu
IPEX commit: 474a6b3cb
Build type: Release

OS: SUSE Linux Enterprise Server 15 SP4 (x86_64)
GCC version: (Spack GCC) 12.2.0
Clang version: N/A
IGC version: 2024.1.0 (2024.1.0.20240308)
CMake version: version 3.27.5
Libc version: glibc-2.31

Python version: 3.9.18 (tags/v3.9.18-26-g6b320c3b2f6-dirty:6b320c3b2f6, Sep 28 2023, 00:35:27)  [GCC 13.2.0] (64-bit runtime)
Python platform: Linux-5.14.21-150400.24.55-default-x86_64-with-glibc2.31
Is XPU available: True
DPCPP runtime version: latest
MKL version: latest
GPU models and configuration: 
[0] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[1] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[2] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[3] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[4] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[5] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[6] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[7] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[8] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[9] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[10] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[11] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
Intel OpenCL ICD version: N/A
Level Zero version: N/A

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          208
On-line CPU(s) list:             0-207
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU Max 9470C
CPU family:                      6
Model:                           143
Thread(s) per core:              2
Core(s) per socket:              52
Socket(s):                       2
Stepping:                        8
Frequency boost:                 enabled
CPU max MHz:                     2001.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4000.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr avx512_fp16 amx_tile flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       4.9 MiB (104 instances)
L1i cache:                       3.3 MiB (104 instances)
L2 cache:                        208 MiB (104 instances)
L3 cache:                        210 MiB (2 instances)
NUMA node(s):                    4
NUMA node0 CPU(s):               0-51,104-155
NUMA node1 CPU(s):               52-103,156-207
NUMA node2 CPU(s):               
NUMA node3 CPU(s):               
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==2.1.30+xpu
[pip3] numpy==1.24.4
[pip3] torch==2.1.0.post2+cxx11.abi
[pip3] torch-tb-profiler==0.4.3
[pip3] torchvision==0.16.0.post2+cxx11.abi
[conda] intel-extension-for-pytorch 2.1.30+xpu               pypi_0    pypi
[conda] mkl                       2024.1.0              intel_642    intel
[conda] mkl-dpcpp                 2024.1.0              intel_642    intel
[conda] mkl-service               2.4.0           py39hc591bdc_44    intel
[conda] mkl_fft                   1.3.8           py39h6b114c4_70    intel
[conda] mkl_random                1.2.4           py39h841069b_90    intel
[conda] mkl_umath                 0.1.1           py39h843e89b_100    intel
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] onemkl-sycl-blas          2024.1.0              intel_642    intel
[conda] onemkl-sycl-datafitting   2024.1.0              intel_642    intel
[conda] onemkl-sycl-dft           2024.1.0              intel_642    intel
[conda] onemkl-sycl-lapack        2024.1.0              intel_642    intel
[conda] onemkl-sycl-rng           2024.1.0              intel_642    intel
[conda] onemkl-sycl-sparse        2024.1.0              intel_642    intel
[conda] onemkl-sycl-stats         2024.1.0              intel_642    intel
[conda] onemkl-sycl-vm            2024.1.0              intel_642    intel
[conda] torch                     2.1.0.post2+cxx11.abi          pypi_0    pypi
[conda] torchvision               0.16.0.post2+cxx11.abi          pypi_0    pypi
```

# Environment 3

```
Collecting environment information...
PyTorch version: 2.1.0.post2+cxx11.abi
PyTorch CXX11 ABI: Yes
IPEX version: 2.1.30.post0
IPEX commit: 97b37e23d
Build type: Release

OS: SUSE Linux Enterprise Server 15 SP4 (x86_64)
GCC version: (Spack GCC) 12.2.0
Clang version: N/A
IGC version: 2024.1.0 (2024.1.0.20240308)
CMake version: version 3.27.5
Libc version: glibc-2.31

Python version: 3.9.18 (tags/v3.9.18-26-g6b320c3b2f6-dirty:6b320c3b2f6, Sep 28 2023, 00:35:27)  [GCC 13.2.0] (64-bit runtime)
Python platform: Linux-5.14.21-150400.24.55-default-x86_64-with-glibc2.31
Is XPU available: True
DPCPP runtime version: latest
MKL version: latest
GPU models and configuration: 
[0] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[1] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[2] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[3] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[4] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[5] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[6] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[7] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[8] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[9] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[10] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
[11] _DeviceProperties(name='Intel(R) Data Center GPU Max 1550', platform_name='Intel(R) Level-Zero', dev_type='gpu', driver_version='1.3.27642', has_fp64=1, total_memory=65536MB, max_compute_units=448, gpu_eu_count=448)
Intel OpenCL ICD version: N/A
Level Zero version: N/A

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          208
On-line CPU(s) list:             0-207
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) CPU Max 9470C
CPU family:                      6
Model:                           143
Thread(s) per core:              2
Core(s) per socket:              52
Socket(s):                       2
Stepping:                        8
Frequency boost:                 enabled
CPU max MHz:                     2001.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4000.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr avx512_fp16 amx_tile flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       4.9 MiB (104 instances)
L1i cache:                       3.3 MiB (104 instances)
L2 cache:                        208 MiB (104 instances)
L3 cache:                        210 MiB (2 instances)
NUMA node(s):                    4
NUMA node0 CPU(s):               0-51,104-155
NUMA node1 CPU(s):               52-103,156-207
NUMA node2 CPU(s):               
NUMA node3 CPU(s):               
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] intel_extension_for_pytorch==2.1.30.post0
[pip3] numpy==1.23.5
[pip3] torch==2.1.0.post2+cxx11.abi
[pip3] torchvision==0.16.0.post2+cxx11.abi
[conda] intel-extension-for-pytorch 2.1.30+xpu               pypi_0    pypi
[conda] mkl                       2024.1.0              intel_642    intel
[conda] mkl-dpcpp                 2024.1.0              intel_642    intel
[conda] mkl-service               2.4.0           py39hc591bdc_44    intel
[conda] mkl_fft                   1.3.8           py39h6b114c4_70    intel
[conda] mkl_random                1.2.4           py39h841069b_90    intel
[conda] mkl_umath                 0.1.1           py39h843e89b_100    intel
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] onemkl-sycl-blas          2024.1.0              intel_642    intel
[conda] onemkl-sycl-datafitting   2024.1.0              intel_642    intel
[conda] onemkl-sycl-dft           2024.1.0              intel_642    intel
[conda] onemkl-sycl-lapack        2024.1.0              intel_642    intel
[conda] onemkl-sycl-rng           2024.1.0              intel_642    intel
[conda] onemkl-sycl-sparse        2024.1.0              intel_642    intel
[conda] onemkl-sycl-stats         2024.1.0              intel_642    intel
[conda] onemkl-sycl-vm            2024.1.0              intel_642    intel
[conda] torch                     2.1.0.post2+cxx11.abi          pypi_0    pypi
[conda] torchvision               0.16.0.post2+cxx11.abi          pypi_0    pypi
```

**Comment by Vasud-ha** [comment]
Hi @garrett361, thanks for reporting it, we will check and get back to you.

**Comment by Vasud-ha** [comment]
Hi @garrett361 , I am not able to reproduce this issue getting this key error
![image](https://github.com/intel/intel-extension-for-pytorch/assets/106226674/d7491d0d-ebbf-437d-810f-651bc5f05c34)

**Comment by garrett361** [comment]
Hi @Vasud-ha, please see my [response here](https://github.com/intel/intel-extension-for-pytorch/issues/647#issuecomment-2152498016), for a similar error message.

**Comment by Vasud-ha** [comment]
Hi @garrett361, getting this issue with the script shared, could you suggest how to run this script?
![image](https://github.com/intel/intel-extension-for-pytorch/assets/106226674/d497461e-b2b0-4ad8-a1e5-23450160feca)

**Comment by garrett361** [comment]
Also, similar to [this comment](https://github.com/intel/intel-extension-for-pytorch/issues/640#issuecomment-2158588342), I found that this OOM only occurs when the model size is sufficiently large. If I change `d_model` from `2**14` to `2**13` the OOM goes away.

**Comment by Vasud-ha** [comment]
Hi @garrett361, I am using a multi-node environment it is an Intel IDC instance that has multiple Intel Data Centre GPU max 1100, could you please share the command that you used to launch the processes?

**Comment by garrett361** [comment]
It depends a bit on how your system is set up, but ssh-ing into each node and using [torchrun](https://pytorch.org/docs/stable/elastic/run.html) is maybe the easiest way.

**Comment by garrett361** [comment]
Noting that the env vars that solve the OOMs in #640 do _not_ solve the OOMs in this case. [See comments here.](https://github.com/intel/intel-extension-for-pytorch/issues/640#issuecomment-2189118145)

**Comment by xiguiw** [comment]
@garrett361 
oneAPI base toolkit 2024.2.1 and IPEX 2.1.40 released. 
I verified this issue is resolved in oneAPI 2024.2.1 + IPEX 2.1.40. 

```
Using Versions: torch.__version__='2.1.0.post3+cxx11.abi', ipex.__version__='2.1.40+xpu', torch_ccl.__version__='2.1.400+xpu'
Using Versions: torch.__version__='2.1.0.post3+cxx11.abi', ipex.__version__='2.1.40+xpu', torch_ccl.__version__='2.1.400+xpu'

batch_size=1, d_model=16384, n_layers=4, max_steps=500, parallelization='fsdp'

rank 15
local_rank 3
batch_size=1, d_model=16384, n_layers=4, max_steps=500, parallelization='fsdp'
device=device(type='xpu', index=3), BACKEND='ccl'

inputs= torch.Size([1, 16384]) inputs= torch.Size([1, 16384]) inputs= torch.Size([1, 16384]) inputs= torch.Size([1, 16384]) inputs= torch.Size([1, 16384]) inputs= torch.Size([1, 16384]) inputs= torch.Size([1, 16384]) inputs= torch.Size([1, 16384]) inputs= rank=1, parallelization='fsdp'
rank=3, parallelization='fsdp'
rank=10, parallelization='fsdp'
****************************************
Running max_steps=500, batch_size=1 across 24 GPUs with

2024:08:14-19:47:55:(3788606) |CCL_WARN| MPI was initialized externally, CCL-MPI specific environment is ignored


....
[rank=7]: step=496 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=1]: step=496 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=3]: step=496 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=9]: step=496 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=11]: step=496 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=12]: step=496 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=14]: step=496 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=16]: step=496 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=18]: step=496 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=20]: step=496 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=22]: step=496 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=17]: step=496 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=23]: step=496 memory peak_mem_GiB=5.083704948425293, current_mem_GiB=1.3751473426818848
[rank=15]: step=496 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=19]: step=496 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=21]: step=496 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=13]: step=496 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=0]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=2]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=4]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=6]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=8]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=10]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=1]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=3]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=5]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=7]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=9]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=11]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=12]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=14]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=16]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=18]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=20]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=22]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=17]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=19]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=23]: step=497 memory peak_mem_GiB=5.083704948425293, current_mem_GiB=1.3751473426818848
[rank=13]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=15]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=21]: step=497 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=0]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=2]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=4]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=6]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=8]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=10]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=1]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=3]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=5]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=7]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=9]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=11]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=12]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=14]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=16]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=18]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=20]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=22]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=17]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=21]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=23]: step=498 memory peak_mem_GiB=5.083704948425293, current_mem_GiB=1.3751473426818848
[rank=13]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=15]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=19]: step=498 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=0]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=2]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=4]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=6]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=8]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=10]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=1]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=3]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=5]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=7]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=9]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=11]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=12]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=14]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=16]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=18]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=20]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=22]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=13]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=15]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=17]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=19]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=21]: step=499 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=23]: step=499 memory peak_mem_GiB=5.083704948425293, current_mem_GiB=1.3751473426818848
[rank=0]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=2]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=4]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=6]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=8]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=10]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=1]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=3]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=5]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=7]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=9]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=11]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=12]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=14]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=16]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=18]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=20]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=22]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=17]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=19]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=23]: step=500 memory peak_mem_GiB=5.083704948425293, current_mem_GiB=1.3751473426818848
[rank=13]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=15]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
[rank=21]: step=500 memory peak_mem_GiB=5.0420355796813965, current_mem_GiB=1.3751473426818848
```

**Comment by garrett361** [comment]
Excellent, thank you for the update @xiguiw !   I will close this out.

Also, is `ipex` still needed? I saw that `torch==2.4` offers [intel gpu support if built from source.](https://pytorch.org/docs/stable/notes/get_start_xpu.html)

**Comment by xiguiw** [comment]
> Excellent, thank you for the update @xiguiw ! I will close this out.
> 
> Also, is `ipex` still needed? I saw that `torch==2.4` offers [intel gpu support if built from source.](https://pytorch.org/docs/stable/notes/get_start_xpu.html)

@garrett361 

Thank you for your patience and support!

Stock PyTorch Intel GPU support is experimental for now. In the short-term IPEX is still needed.
For custom workloads please try with PyTorch first. If it does not meet your expectation, please turn back to IPEX.
