### ISSUE TITLE
Sanity Check Failed on A770

### ISSUE THREAD

**Issue by chunsheong** [intel/intel-extension-for-pytorch#708]
### Describe the bug

Followed the installation steps here. https://intel.github.io/intel-extension-for-pytorch/index.html#installation?platform=gpu&version=v2.3.110%2bxpu&os=linux%2fwsl2&package=pip

python -c "import torch; import intel_extension_for_pytorch as ipex; print(torch.__version__); print(ipex.__version__); [print(f'[{i}]: {torch.xpu.get_device_properties(i)}') for i in range(torch.xpu.device_count())];"

2.3.1+cxx11.abi
2.3.110+xpu
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/ComfyUI/venv/lib/python3.10/site-packages/torch/xpu/__init__.py", line 57, in device_count
    return torch._C._xpu_getDeviceCount()
RuntimeError: Native API failed. Native API returns: -1102 (PI_ERROR_UNINITIALIZED) -1102 (PI_ERROR_UNINITIALIZED)

### Versions

2.3.110+xpu

**Comment by chsasank** [comment]
Can confirm this issue. Looks like this is similar to #702

**Comment by alexsin368** [comment]
@chunsheong let me try reproducing this issue on my end and get back to you

**Comment by xiguiw** [comment]
@chunsheong @chsasank @alexsin368 
Similar issue fixed in 702. Please refer to [702](https://github.com/intel/intel-extension-for-pytorch/issues/708)

**Comment by alexsin368** [comment]
@chunsheong this is the solution from issue #702: 

If it is 6.0.29 in conda, please update it to 6.0.30 and version above by:

conda install -c conda-forge libstdcxx-ng or
preload the one in /usr/lib
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30

Try that and let us know if it resolves your issue.
